merge: new changes

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,9 +17,21 @@ jobs:
           fetch-depth: 0
           submodules: true
 
+      - name: Get last tag
+        id: last_tag
+        uses: oprypin/find-latest-tag@v1
+        continue-on-error: true
+        with:
+          token: ${{ secrets.GITHUB_TOKEN }}
+          repository: ${{ github.repository }}
+          releases-only: true
+
       - name: Get next version code
         id: next_ver_code
-        run: ./scripts/workflow/build.sh next_ver_code
+        run: |
+          TAG="${{ steps.last_tag.outputs.tag }}"
+          if [ -z "$TAG" ]; then TAG=0; fi
+          echo "NEXT_VER_CODE=$((TAG + 1))" >> $GITHUB_OUTPUT
 
       - name: Build modules/APKs
         run: ./build.sh
@@ -30,7 +42,20 @@ jobs:
 
       - name: Get output
         id: get_output
-        run: ./scripts/workflow/build.sh get_output
+        run: |
+          DELIM="$(openssl rand -hex 8)"
+          echo "BUILD_LOG<<${DELIM}" >> "$GITHUB_OUTPUT"
+          cat build.md >> "$GITHUB_OUTPUT"
+          echo "${DELIM}" >> "$GITHUB_OUTPUT"
+          cp -f build.md build.tmp
+
+          yt_op=$(find build -maxdepth 1 -name "youtube-*-magisk-*.zip" -printf '%P\n')
+          yt_op=$(echo "$yt_op" | sed "s/youtube-revanced-magisk-//" | sed "s/-all.zip//")
+          if [ -z "$yt_op" ]; then
+            echo "RELEASE_NAME=ReVanced" >> $GITHUB_OUTPUT
+          else
+            echo "RELEASE_NAME=$yt_op" >> $GITHUB_OUTPUT
+          fi
 
       - name: Upload modules to release
         uses: svenstaro/upload-release-action@v2
@@ -41,14 +66,83 @@ jobs:
           release_name: ${{ steps.get_output.outputs.RELEASE_NAME }}
           tag: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
           file_glob: true
-          overwrite: false
+          overwrite: true
 
-      - name: Update changelog and Magisk update jsons
-        id: update_config
+      - name: Report to Telegram
         env:
-          NEXT_VER_CODE: ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
-          RELEASE_NAME: ${{ steps.get_output.outputs.RELEASE_NAME }}
-        run: ./scripts/workflow/build.sh update_config
+          TG_TOKEN: ${{ secrets.TG_TOKEN }}
+          TG_CHAT: ${{ secrets.TG_CHAT }}
+        if: env.TG_TOKEN != null
+        run: |
+          source utils.sh
+          cd build || echo "build folder not found"
+
+          NL=$'\n'
+          APKS=""
+          MODULES=""
+          for OUTPUT in *revanced*; do
+            DL_URL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+            if [[ $OUTPUT = *.apk ]]; then
+              APKS+="${NL}📦[${OUTPUT}](${DL_URL})"
+            elif [[ $OUTPUT = *.zip ]]; then
+              MODULES+="${NL}📦[${OUTPUT}](${DL_URL})"
+            fi
+          done
+
+          MICRO_G=$(wget -q -nv -O- https://api.github.com/repos/inotia00/VancedMicroG/releases/latest)
+          MICRO_G_URL=$(echo "$MICRO_G" | json_get 'browser_download_url' | grep 'apk')
+          APKS+="${NL}📦[Micro-G](${MICRO_G_URL})"
+
+          MODULES=${MODULES#"$NL"}
+          APKS=${APKS#"$NL"}
+
+          BODY="$(sed 's/^\* \*\*/↪ \*\*/g; s/^\* `/↪ \*\*/g; s/`/\*/g; s/^\* /\↪/g; s/\*\*/\*/g; s/###//g;' ../build.md)"
+          MSG="*New build!*
+          *ReVanced*
+
+          ${BODY}
+
+          *▼ Download Links:*
+          Modules:
+          ${MODULES}
+
+          APKs:
+          ${APKS}
+          "
+          echo "'$MSG'"
+          POST="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
+          curl -X POST --data-urlencode "parse_mode=Markdown" --data-urlencode "text=${MSG}" --data-urlencode "chat_id=${TG_CHAT}" "$POST"
+
+      - name: Update changelog and Magisk update json
+        id: update_config
+        run: |
+          git checkout -f update || git switch --discard-changes --orphan update
+          cp -f build.tmp build.md
+          get_update_json() {
+            echo "{
+            \"version\": \"$1\",
+            \"versionCode\": ${{ steps.next_ver_code.outputs.NEXT_VER_CODE}},
+            \"zipUrl\": \"$2\",
+            \"changelog\": \"https://raw.githubusercontent.com/$GITHUB_REPOSITORY/update/build.md\"
+          }"
+          }
+
+          cd build || echo "build folder not found"
+          for OUTPUT in *revanced*.zip; do
+            [ "$OUTPUT" = "*revanced*.zip" ] && continue
+            ZIP_S=$(unzip -p "$OUTPUT" module.prop)
+            if ! UPDATE_JSON=$(echo "$ZIP_S" | grep updateJson); then
+              continue
+            fi
+            UPDATE_JSON="${UPDATE_JSON##*/}"
+            VER=$(echo "$ZIP_S" | grep version=)
+            VER="${VER##*=}"
+            DLURL="$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/download/${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}/${OUTPUT}"
+            get_update_json "$VER" "$DLURL" >"../$UPDATE_JSON"
+          done
+          cd ..
+
+          find . -name "*-update.json" | grep . || : >dummy-update.json
 
       - uses: stefanzweifel/git-auto-commit-action@v4
         with:
@@ -57,15 +151,9 @@ jobs:
           file_pattern: build.md *-update.json
           commit_message: Bump version ${{ steps.next_ver_code.outputs.NEXT_VER_CODE }}
 
-      - name: Checkout to main
-        run: git checkout -f main || git switch --discard-changes --orphan main
-
-      - name: Report to Telegram
-        id: telegram_release
-        env:
-          TELEGRAM_MSG: ${{ steps.update_config.outputs.TELEGRAM_MSG }}
-          TG_TOKEN: ${{ secrets.TG_TOKEN }}
-          TG_CHAT: ${{ secrets.TG_CHAT }}
-        if: env.TG_TOKEN != null
-        run: ./scripts/workflow/build.sh telegram_release
+      - uses: actions/upload-artifact@v3
+        with:
+          name: logs
+          path: logs
+          if-no-files-found: ignore
 
diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,7 +2,7 @@ name: CI
 on:
   workflow_dispatch:
   schedule:
-    - cron: "0 16 */7 * *"
+    - cron: "0 16 * * *"
 
 jobs:
   check:
@@ -14,14 +14,53 @@ jobs:
           fetch-depth: 0
 
       - name: Should build?
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         id: should_build
-        run: ./scripts/workflow/ci.sh should_build
+        shell: bash
+        run: |
+          source utils.sh
+          toml_prep "$(cat config.toml)"
+
+          is_youtube_latest() {
+            t=$(toml_get_table YouTube)
+            v=$(toml_get "$t" "version") || v=
+            if [ "$v" = latest ]; then
+              cur_yt=$(sed -n 's/.*YouTube: \(.*\)/\1/p' build.md | xargs)
+              [ -z "$cur_yt" ] && return 1 # empty, fail=>dont build
+              aav=$(toml_get "$t" "allow-alpha-version") || aav=false
+              last_ver=$(get_apkmirror_vers youtube "$aav" | get_largest_ver)
+              [ -z "$last_ver" ] && return 1 # cant fetch, dont build
+              echo "current yt version: '$cur_yt'"
+              echo "latest yt version: '$last_ver'"
+              [ "$cur_yt" != "$last_ver" ] # test success=>build, fail=>dont build
+            else
+              return 1 # not experimental, dont build
+            fi
+          }
+
+          is_patches_latest() {
+            PATCHES_SRC=$(toml_get "$(toml_get_table "")" patches-source) || PATCHES_SRC="revanced/revanced-patches"
+            last_patches_url=$(wget -nv --header="Authorization: token ${{ secrets.GITHUB_TOKEN }}" -O- https://api.github.com/repos/${PATCHES_SRC}/releases/latest | json_get 'browser_download_url' | grep 'jar')
+            last_patches=${last_patches_url##*/}
+            cur_patches=$(sed -n 's/.*Patches: \(.*\)/\1/p' build.md | xargs)
+
+            echo "current patches version: $cur_patches"
+            echo "latest patches version: $last_patches"
+            [ "$cur_patches" != "$last_patches" ] # test success=>build, fail=>dont build
+          }
+
+          if ! git checkout update; then
+            echo "first time building!"
+            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
+          elif is_patches_latest || is_youtube_latest; then
+            echo "build!"
+            echo "SHOULD_BUILD=1" >> $GITHUB_OUTPUT
+          else
+            echo "dont build!"
+            echo "SHOULD_BUILD=0" >> $GITHUB_OUTPUT
+          fi
 
     outputs:
       SHOULD_BUILD: ${{ steps.should_build.outputs.SHOULD_BUILD }}
-
   config_check:
     runs-on: ubuntu-latest
     needs: check
@@ -45,7 +84,15 @@ jobs:
       - name: On Failure
         id: send_telegram_failure
         if: ${{ failure() }}
-        run: ./scripts/workflow/ci.sh send_telegram_failure
+        run: |
+          POST="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"
+          URL="[Failed Action]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)"
+
+          MSG="*Check patches config*
+          ${URL}"
+
+          curl -X POST --data-urlencode "parse_mode=Markdown" --data-urlencode "text=${MSG}" --data-urlencode "chat_id=${TG_DEV}" "$POST" >/dev/null
+          echo "SHOULD_BUILD=0" >>$GITHUB_OUTPUT
 
       - name: On success
         id: config
@@ -54,7 +101,6 @@ jobs:
 
     outputs:
       SHOULD_BUILD: ${{ steps.config.outputs.SHOULD_BUILD }}
-
   build:
     permissions: write-all
     needs: config_check
